version: '3.7'
services:
  main:
    build: .
    restart: on-failure
    command: python ./main.py --config ./config.toml --repeat 3600
    # command: python ./main.py --config ./config.toml --repeat 0 --sendanchor no